// Authentic B2B Lead Dataset matching Apollo People Search Screenshot & Full Dataset
export const INITIAL_PEOPLE_DATA = [
  {
    id: 1,
    name: 'Sheng Fu',
    firstName: 'Sheng',
    lastName: 'Fu',
    avatar: 'SF',
    jobTitle: 'Chief Growth Officer',
    company: 'Cheetah Mobile',
    companyLogo: 'CM',
    industry: 'SaaS & Mobile Tech',
    location: 'Beijing, China',
    country: 'China',
    email: 'sheng.fu@cmcm.com',
    emailStatus: 'Verified',
    phone: '+86 10 6292 7777',
    phoneStatus: 'Verified',
    seniority: 'C-Suite',
    department: 'Executive',
    employees: '1001–5000',
    employeeCountNum: 2500,
    revenue: '$100M+',
    score: 95,
    linkedin: 'https://linkedin.com/in/shengfu',
    website: 'www.cmcm.com',
    createdAt: '2026-08-15',
    lastActivity: '10 mins ago',
    saved: false,
    lists: ['Hot Leads'],
    bio: 'Tech entrepreneur & Chief Growth Officer leading mobile software and AI products.'
  },
  {
    id: 2,
    name: 'Liz Ryan',
    firstName: 'Liz',
    lastName: 'Ryan',
    avatar: 'LR',
    jobTitle: 'Founder & CEO',
    company: 'Human Workplace',
    companyLogo: 'HW',
    industry: 'Professional Services',
    location: 'Boulder, CO',
    country: 'United States',
    email: 'liz@humanworkplace.com',
    emailStatus: 'Verified',
    phone: '+1 (303) 441-2910',
    phoneStatus: 'Verified',
    seniority: 'C-Suite',
    department: 'Executive',
    employees: '51–200',
    employeeCountNum: 120,
    revenue: '$10M–$20M',
    score: 94,
    linkedin: 'https://linkedin.com/in/lizryan',
    website: 'www.humanworkplace.com',
    createdAt: '2026-08-18',
    lastActivity: '1 hour ago',
    saved: true,
    lists: ['SaaS Founders'],
    bio: 'Founder & CEO, author, speaker, and advocate for human-centric leadership & HR transformation.'
  },
  {
    id: 3,
    name: 'Jeffrey Towson',
    firstName: 'Jeffrey',
    lastName: 'Towson',
    avatar: 'JT',
    jobTitle: 'Managing Partner',
    company: 'Towson Group Tech Advisory',
    companyLogo: 'TG',
    industry: 'Consulting & Strategy',
    location: 'Riyadh, Saudi Arabia',
    country: 'Saudi Arabia',
    email: 'jeffrey@towsontech.com',
    emailStatus: 'Verified',
    phone: '+966 11 450 8899',
    phoneStatus: 'Available',
    seniority: 'C-Suite',
    department: 'Executive',
    employees: '11–50',
    employeeCountNum: 35,
    revenue: '$5M–$10M',
    score: 91,
    linkedin: 'https://linkedin.com/in/jeffreytowson',
    website: 'www.towsontech.com',
    createdAt: '2026-08-20',
    lastActivity: '3 hours ago',
    saved: false,
    lists: ['Enterprise Prospects'],
    bio: 'Strategy consultant, former PE investor, and professor specializing in digital platforms and tech expansion.'
  },
  {
    id: 4,
    name: 'Christine Lagarde',
    firstName: 'Christine',
    lastName: 'Lagarde',
    avatar: 'CL',
    jobTitle: 'President',
    company: 'European Central Bank',
    companyLogo: 'EC',
    industry: 'Financial Services',
    location: 'Frankfurt, Germany',
    country: 'Germany',
    email: 'christine.lagarde@ecb.europa.eu',
    emailStatus: 'Verified',
    phone: '+49 69 1344 0',
    phoneStatus: 'Verified',
    seniority: 'C-Suite',
    department: 'Executive',
    employees: '5000+',
    employeeCountNum: 4000,
    revenue: '$100M+',
    score: 98,
    linkedin: 'https://linkedin.com/in/christinelagarde',
    website: 'www.ecb.europa.eu',
    createdAt: '2026-07-10',
    lastActivity: 'Just now',
    saved: true,
    lists: ['Enterprise Prospects'],
    bio: 'President of the European Central Bank and former Managing Director of the International Monetary Fund.'
  },
  {
    id: 5,
    name: 'Aarav Sharma',
    firstName: 'Aarav',
    lastName: 'Sharma',
    avatar: 'AS',
    jobTitle: 'VP Sales',
    company: 'TechNova',
    companyLogo: 'TN',
    industry: 'SaaS',
    location: 'Mumbai, India',
    country: 'India',
    email: 'aarav.sharma@technova.io',
    emailStatus: 'Verified',
    phone: '+91 98201 44812',
    phoneStatus: 'Verified',
    seniority: 'VP',
    department: 'Sales',
    employees: '201–500',
    employeeCountNum: 350,
    revenue: '$10M–$50M',
    score: 92,
    linkedin: 'https://linkedin.com/in/aaravsharma-sales',
    website: 'www.technova.io',
    createdAt: '2026-08-15',
    lastActivity: '2 hours ago',
    saved: true,
    lists: ['India Sales Leaders', 'Hot Leads'],
    bio: 'Experienced VP of Sales leading enterprise software expansion across APAC region with 14+ years in SaaS.'
  },
  {
    id: 6,
    name: 'Ananya Verma',
    firstName: 'Ananya',
    lastName: 'Verma',
    avatar: 'AV',
    jobTitle: 'Head of Marketing',
    company: 'GrowthLabs',
    companyLogo: 'GL',
    industry: 'Marketing & Advertising',
    location: 'Delhi, India',
    country: 'India',
    email: 'ananya@growthlabs.com',
    emailStatus: 'Verified',
    phone: '+91 99102 88319',
    phoneStatus: 'Available',
    seniority: 'Head',
    department: 'Marketing',
    employees: '51–200',
    employeeCountNum: 140,
    revenue: '$5M–$10M',
    score: 87,
    linkedin: 'https://linkedin.com/in/ananya-verma-growth',
    website: 'www.growthlabs.com',
    createdAt: '2026-08-20',
    lastActivity: '1 day ago',
    saved: false,
    lists: ['Marketing Directors'],
    bio: 'Growth marketing strategist specializing in demand generation, account-based marketing, and inbound pipelines.'
  },
  {
    id: 7,
    name: 'Matt Curl',
    firstName: 'Matt',
    lastName: 'Curl',
    avatar: 'MC',
    jobTitle: 'Chief Executive Officer',
    company: 'Apollo.io',
    companyLogo: 'AP',
    industry: 'Sales Intelligence',
    location: 'San Francisco, CA',
    country: 'United States',
    email: 'mc@apollo.io',
    emailStatus: 'Verified',
    phone: '+1 (415) 892-0192',
    phoneStatus: 'Verified',
    seniority: 'C-Suite',
    department: 'Executive',
    employees: '501–1000',
    employeeCountNum: 850,
    revenue: '$100M+',
    score: 98,
    linkedin: 'https://linkedin.com/in/mattcurl',
    website: 'www.apollo.io',
    createdAt: '2026-07-10',
    lastActivity: 'Just now',
    saved: true,
    lists: ['Hot Leads', 'SaaS Founders'],
    bio: 'Co-founder & CEO driving next-gen sales intelligence and GTM workflow execution.'
  },
  {
    id: 8,
    name: 'Sarah Jenkins',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    avatar: 'SJ',
    jobTitle: 'VP of Sales',
    company: 'Stripe',
    companyLogo: 'ST',
    industry: 'FinTech',
    location: 'New York, NY',
    country: 'United States',
    email: 's.jenkins@stripe.com',
    emailStatus: 'Verified',
    phone: '+1 (212) 441-9981',
    phoneStatus: 'Verified',
    seniority: 'VP',
    department: 'Sales',
    employees: '5000+',
    employeeCountNum: 7500,
    revenue: '$100M+',
    score: 95,
    linkedin: 'https://linkedin.com/in/sarahjenkins-fintech',
    website: 'www.stripe.com',
    createdAt: '2026-08-01',
    lastActivity: '3 hours ago',
    saved: true,
    lists: ['Enterprise Prospects'],
    bio: 'Oversees global commercial sales teams for payments infrastructure and revenue software.'
  },
  {
    id: 9,
    name: 'David Chen',
    firstName: 'David',
    lastName: 'Chen',
    avatar: 'DC',
    jobTitle: 'Head of Growth',
    company: 'Notion',
    companyLogo: 'NT',
    industry: 'Productivity Software',
    location: 'Austin, TX',
    country: 'United States',
    email: 'david.c@m.notion.so',
    emailStatus: 'Verified',
    phone: '+1 (512) 330-8812',
    phoneStatus: 'Available',
    seniority: 'Head',
    department: 'Marketing',
    employees: '1001–5000',
    employeeCountNum: 2400,
    revenue: '$50M–$100M',
    score: 91,
    linkedin: 'https://linkedin.com/in/davidchengrowth',
    website: 'www.notion.so',
    createdAt: '2026-08-12',
    lastActivity: 'Yesterday',
    saved: false,
    lists: ['SaaS Decision Makers'],
    bio: 'Product-led growth expert scaling enterprise workspace adoption globally.'
  },
  {
    id: 10,
    name: 'Elena Rostova',
    firstName: 'Elena',
    lastName: 'Rostova',
    avatar: 'ER',
    jobTitle: 'Director of RevOps',
    company: 'Figma',
    companyLogo: 'FG',
    industry: 'SaaS',
    location: 'Seattle, WA',
    country: 'United States',
    email: 'elena@figma.com',
    emailStatus: 'Verified',
    phone: '+1 (206) 773-1029',
    phoneStatus: 'Verified',
    seniority: 'Director',
    department: 'Operations',
    employees: '1001–5000',
    employeeCountNum: 1800,
    revenue: '$50M–$100M',
    score: 89,
    linkedin: 'https://linkedin.com/in/elenarostova',
    website: 'www.figma.com',
    createdAt: '2026-08-18',
    lastActivity: '4 hours ago',
    saved: true,
    lists: ['Hot Leads'],
    bio: 'Revenue Operations Director connecting marketing, sales, and customer success tech stack.'
  }
];

const generateMoreLeads = () => {
  const firstNames = ['Arjun', 'Tanvi', 'Kabir', 'Maya', 'Siddharth', 'Isha', 'Varun', 'Rhea', 'Aditya', 'Meera', 'Daniel', 'Chloe', 'James', 'Grace', 'Benjamin', 'Zoe', 'Lucas', 'Mia', 'Henry', 'Lily'];
  const lastNames = ['Gupta', 'Chawla', 'Deshmukh', 'Singhal', 'Kulkarni', 'Bhasin', 'Saxena', 'Choudhury', 'Joshi', 'Reddy', 'Brown', 'Davis', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'White', 'Harris', 'Martin', 'Clark'];
  const titles = ['VP Sales', 'Sales Director', 'Head of Sales', 'Enterprise Account Executive', 'Director of RevOps', 'VP Marketing', 'Head of Growth', 'Chief Technology Officer', 'Director of Engineering', 'Senior SDR Manager'];
  const companies = ['TechNova', 'GrowthLabs', 'Apollo.io', 'Stripe', 'Notion', 'Figma', 'HubSpot', 'Infosys', 'Freshworks', 'Razorpay', 'Datadog', 'TCS', 'Snowflake', 'Postman', 'Microsoft', 'Google', 'Amazon', 'Zomato'];
  const cities = [
    { city: 'Mumbai, India', country: 'India' },
    { city: 'Bengaluru, India', country: 'India' },
    { city: 'Delhi, India', country: 'India' },
    { city: 'Hyderabad, India', country: 'India' },
    { city: 'San Francisco, CA', country: 'United States' },
    { city: 'New York, NY', country: 'United States' },
    { city: 'Austin, TX', country: 'United States' },
    { city: 'Seattle, WA', country: 'United States' },
    { city: 'London, UK', country: 'United Kingdom' },
    { city: 'Manchester, UK', country: 'United Kingdom' }
  ];
  const industries = ['SaaS', 'FinTech', 'Marketing & Advertising', 'Productivity Software', 'Sales Intelligence', 'IT Services', 'Cloud & Analytics', 'E-Commerce', 'Artificial Intelligence'];
  const seniorities = ['C-Suite', 'VP', 'Director', 'Head', 'Manager', 'Senior'];
  const departments = ['Sales', 'Marketing', 'Engineering', 'HR', 'Finance', 'Operations', 'IT', 'Product', 'Customer Success'];
  const empRanges = ['1–10', '11–50', '51–200', '201–500', '501–1000', '1001–5000', '5000+'];
  const empNums = [8, 35, 120, 350, 780, 2400, 8500];
  const emailStatuses = ['Verified', 'Verified', 'Verified', 'Unverified', 'Catch-all'];

  const extra = [];
  for (let i = 11; i <= 100; i++) {
    const fn = firstNames[(i * 3) % firstNames.length];
    const ln = lastNames[(i * 7) % lastNames.length];
    const title = titles[i % titles.length];
    const comp = companies[i % companies.length];
    const loc = cities[i % cities.length];
    const ind = industries[i % industries.length];
    const sen = seniorities[i % seniorities.length];
    const dept = departments[i % departments.length];
    const empIdx = i % empRanges.length;
    const empRange = empRanges[empIdx];
    const empNum = empNums[empIdx];
    const status = emailStatuses[i % emailStatuses.length];
    const score = 65 + (i * 13) % 33;
    const cleanComp = comp.toLowerCase().replace(/[^a-z0-9]/g, '');

    extra.push({
      id: i,
      name: `${fn} ${ln}`,
      firstName: fn,
      lastName: ln,
      avatar: `${fn[0]}${ln[0]}`,
      jobTitle: title,
      company: comp,
      companyLogo: comp.substring(0, 2).toUpperCase(),
      industry: ind,
      location: loc.city,
      country: loc.country,
      email: `${fn.toLowerCase()}.${ln.toLowerCase()}@${cleanComp}.com`,
      emailStatus: status,
      phone: loc.country === 'India' ? `+91 ${98000 + i} ${10000 + i}` : loc.country === 'United Kingdom' ? `+44 20 ${7900 + i} ${1000 + i}` : `+1 (${400 + (i % 50)}) 555-${1000 + i}`,
      phoneStatus: status === 'Verified' ? 'Verified' : 'Available',
      seniority: sen,
      department: dept,
      employees: empRange,
      employeeCountNum: empNum,
      revenue: empNum > 5000 ? '$100M+' : empNum > 500 ? '$20M–$50M' : '$5M–$20M',
      score: score,
      linkedin: `https://linkedin.com/in/${fn.toLowerCase()}-${ln.toLowerCase()}`,
      website: `www.${cleanComp}.com`,
      createdAt: '2026-08-25',
      lastActivity: `${(i % 5) + 1} days ago`,
      saved: i % 4 === 0,
      lists: i % 3 === 0 ? ['Hot Leads'] : i % 5 === 0 ? ['SaaS Decision Makers'] : [],
      bio: `High performance ${title} with proven track record in ${ind} scale and execution.`
    });
  }
  return extra;
};

export const FULL_PEOPLE_DATA = [...INITIAL_PEOPLE_DATA, ...generateMoreLeads()];

export const DEFAULT_LISTS = [
  { id: 'list_1', name: 'Hot Leads', count: 18, color: '#ef4444' },
  { id: 'list_2', name: 'SaaS Founders', count: 12, color: '#8b5cf6' },
  { id: 'list_3', name: 'India Sales Leaders', count: 24, color: '#f59e0b' },
  { id: 'list_4', name: 'Enterprise Prospects', count: 15, color: '#3b82f6' },
  { id: 'list_5', name: 'Marketing Directors', count: 9, color: '#10b981' }
];

export const DEFAULT_PERSONAS = [
  {
    id: 'persona_1',
    name: 'SaaS Decision Makers',
    description: 'VPs & C-Suite at B2B SaaS companies with 50-1000 employees.',
    count: 3420,
    filters: { seniority: ['C-Suite', 'VP'], industry: ['SaaS'] }
  },
  {
    id: 'persona_2',
    name: 'Sales Leaders',
    description: 'VPs, Directors, and Heads of Sales in US & India.',
    count: 5120,
    filters: { department: ['Sales'], seniority: ['VP', 'Director', 'Head'] }
  },
  {
    id: 'persona_3',
    name: 'Marketing Leaders',
    description: 'Heads of Marketing & Growth Directors scaling pipeline.',
    count: 2840,
    filters: { department: ['Marketing'] }
  },
  {
    id: 'persona_4',
    name: 'Founders & CEOs',
    description: 'CEOs & Founders of high-growth technology companies.',
    count: 1950,
    filters: { seniority: ['C-Suite'] }
  },
  {
    id: 'persona_5',
    name: 'Enterprise IT Leaders',
    description: 'CTOs & IT Directors at 1000+ employee organizations.',
    count: 4210,
    filters: { department: ['IT', 'Engineering'], employees: ['1001–5000', '5000+'] }
  }
];
